services:
  maipractice:
    image: maipractice
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: animals
